/* Generated By:JavaCC: Do not edit this line. MediawikiScannerConstants.java */
package mo.umac.wikianalysis.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MediawikiScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NEW_LINE = 1;
  /** RegularExpression Id. */
  int SPACE = 2;
  /** RegularExpression Id. */
  int SPECIAL_SYMBOL = 3;
  /** RegularExpression Id. */
  int CHAR = 4;
  /** RegularExpression Id. */
  int PARAMS = 5;
  /** RegularExpression Id. */
  int TABLE_BEGIN = 6;
  /** RegularExpression Id. */
  int TABLE_END = 7;
  /** RegularExpression Id. */
  int TABLE_CAPTION = 8;
  /** RegularExpression Id. */
  int TABLE_ROW = 9;
  /** RegularExpression Id. */
  int TABLE_CELL = 10;
  /** RegularExpression Id. */
  int TABLE_CELL_NL = 11;
  /** RegularExpression Id. */
  int HORLINE = 12;
  /** RegularExpression Id. */
  int HEADER = 13;
  /** RegularExpression Id. */
  int LI_SYMBOL = 14;
  /** RegularExpression Id. */
  int LI = 15;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 16;
  /** RegularExpression Id. */
  int NUM_CHAR = 17;
  /** RegularExpression Id. */
  int ALPHANUM_CHAR = 18;
  /** RegularExpression Id. */
  int IDENTIFIER_CHAR = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;
  /** RegularExpression Id. */
  int URI = 21;
  /** RegularExpression Id. */
  int ALPHA = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;
  /** RegularExpression Id. */
  int HEXDIG = 24;
  /** RegularExpression Id. */
  int URI_GEN_DELIMS = 25;
  /** RegularExpression Id. */
  int URI_SUB_DELIMS = 26;
  /** RegularExpression Id. */
  int URI_UNRESERVED = 27;
  /** RegularExpression Id. */
  int URI_RESERVED = 28;
  /** RegularExpression Id. */
  int URI_SCHEME = 29;
  /** RegularExpression Id. */
  int URI_SCHEME_COMPOSITE = 30;
  /** RegularExpression Id. */
  int URI_PCT_ENCODED = 31;
  /** RegularExpression Id. */
  int URI_PCHAR_FIRST = 32;
  /** RegularExpression Id. */
  int URI_PCHAR = 33;
  /** RegularExpression Id. */
  int URI_QUERY = 34;
  /** RegularExpression Id. */
  int URI_FRAGMENT = 35;
  /** RegularExpression Id. */
  int URI_HIER_PART = 36;
  /** RegularExpression Id. */
  int URI_AUTHORITY = 37;
  /** RegularExpression Id. */
  int URI_USERINFO = 38;
  /** RegularExpression Id. */
  int URI_PATH_ABEMPTY = 39;
  /** RegularExpression Id. */
  int URI_PATH_ABSOLUTE = 40;
  /** RegularExpression Id. */
  int URI_PATH_ROOTLESS = 41;
  /** RegularExpression Id. */
  int URI_SEGMENT = 42;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ = 43;
  /** RegularExpression Id. */
  int URI_SEGMENT_NZ_NC = 44;
  /** RegularExpression Id. */
  int URI_PORT = 45;
  /** RegularExpression Id. */
  int URI_HOST = 46;
  /** RegularExpression Id. */
  int URI_REG_NAME = 47;
  /** RegularExpression Id. */
  int I_TABLE_BEGIN = 48;
  /** RegularExpression Id. */
  int I_TABLE_END = 49;
  /** RegularExpression Id. */
  int I_TABLE_CAPTION = 50;
  /** RegularExpression Id. */
  int I_TABLE_ROW = 51;
  /** RegularExpression Id. */
  int I_TABLE_CELL = 52;
  /** RegularExpression Id. */
  int I_TABLE_CELL_NL = 53;
  /** RegularExpression Id. */
  int I_LIST_ITEM = 54;
  /** RegularExpression Id. */
  int I_HEADER_BEGIN = 55;
  /** RegularExpression Id. */
  int I_HORLINE = 56;
  /** RegularExpression Id. */
  int I_HEADER_END = 57;
  /** RegularExpression Id. */
  int D_TABLE_BEGIN = 58;
  /** RegularExpression Id. */
  int D_TABLE_END = 59;
  /** RegularExpression Id. */
  int D_TABLE_CAPTION = 60;
  /** RegularExpression Id. */
  int D_TABLE_ROW = 61;
  /** RegularExpression Id. */
  int D_TABLE_CELL = 62;
  /** RegularExpression Id. */
  int D_TABLE_CELL_NL = 63;
  /** RegularExpression Id. */
  int D_LIST_ITEM = 64;
  /** RegularExpression Id. */
  int D_HEADER_BEGIN = 65;
  /** RegularExpression Id. */
  int D_HORLINE = 66;
  /** RegularExpression Id. */
  int D_HEADER_END = 67;
  /** RegularExpression Id. */
  int IMAGE_ATTR = 68;
  /** RegularExpression Id. */
  int IMAGE_CAPTION_BEGIN = 69;
  /** RegularExpression Id. */
  int IMAGE_WORD = 70;
  /** RegularExpression Id. */
  int IMAGE_NL = 71;
  /** RegularExpression Id. */
  int IMAGE_END = 72;
  /** RegularExpression Id. */
  int IMAGE_BEGIN = 73;
  /** RegularExpression Id. */
  int TEMPLATE_BEGIN = 74;
  /** RegularExpression Id. */
  int TEMPLATE_END = 75;
  /** RegularExpression Id. */
  int SPACES = 76;
  /** RegularExpression Id. */
  int WORD = 77;
  /** RegularExpression Id. */
  int SYMBOL = 78;
  /** RegularExpression Id. */
  int NL = 79;
  /** RegularExpression Id. */
  int REF_EMPTY = 80;
  /** RegularExpression Id. */
  int REF_BEGIN = 81;
  /** RegularExpression Id. */
  int REF_END = 82;
  /** RegularExpression Id. */
  int TAG_EMPTY = 83;
  /** RegularExpression Id. */
  int TAG_BEGIN = 84;
  /** RegularExpression Id. */
  int TAG_END = 85;
  /** RegularExpression Id. */
  int BOLD = 86;
  /** RegularExpression Id. */
  int ITALIC = 87;
  /** RegularExpression Id. */
  int INT_LINK_BEGIN = 88;
  /** RegularExpression Id. */
  int EXT_LINK_BEGIN = 89;
  /** RegularExpression Id. */
  int HTML_ENTITY = 90;
  /** RegularExpression Id. */
  int EXT_LINK_END = 91;
  /** RegularExpression Id. */
  int INT_LINK_PREFIX = 92;
  /** RegularExpression Id. */
  int INT_LINK_SEPARATOR = 93;
  /** RegularExpression Id. */
  int INT_LINK_SPACES = 94;
  /** RegularExpression Id. */
  int INT_LINK_END = 95;
  /** RegularExpression Id. */
  int INT_LINK_CONTENT = 96;
  /** RegularExpression Id. */
  int INT_LINK_SYMBOL = 97;

  /** Lexical state. */
  int INT_LINK = 0;
  /** Lexical state. */
  int IMAGE = 1;
  /** Lexical state. */
  int INITIAL_CONTEXT = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<PARAMS>",
    "<TABLE_BEGIN>",
    "\"|}\"",
    "<TABLE_CAPTION>",
    "<TABLE_ROW>",
    "<TABLE_CELL>",
    "<TABLE_CELL_NL>",
    "<HORLINE>",
    "<HEADER>",
    "<LI_SYMBOL>",
    "<LI>",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_TABLE_BEGIN>",
    "<I_TABLE_END>",
    "<I_TABLE_CAPTION>",
    "<I_TABLE_ROW>",
    "<I_TABLE_CELL>",
    "<I_TABLE_CELL_NL>",
    "<I_LIST_ITEM>",
    "<I_HEADER_BEGIN>",
    "<I_HORLINE>",
    "<I_HEADER_END>",
    "<D_TABLE_BEGIN>",
    "<D_TABLE_END>",
    "<D_TABLE_CAPTION>",
    "<D_TABLE_ROW>",
    "<D_TABLE_CELL>",
    "<D_TABLE_CELL_NL>",
    "<D_LIST_ITEM>",
    "<D_HEADER_BEGIN>",
    "<D_HORLINE>",
    "<D_HEADER_END>",
    "<IMAGE_ATTR>",
    "\"|\"",
    "<IMAGE_WORD>",
    "<IMAGE_NL>",
    "\"]]\"",
    "<IMAGE_BEGIN>",
    "<TEMPLATE_BEGIN>",
    "\"}}\"",
    "<SPACES>",
    "<WORD>",
    "<SYMBOL>",
    "<NL>",
    "<REF_EMPTY>",
    "<REF_BEGIN>",
    "\"</ref>\"",
    "<TAG_EMPTY>",
    "<TAG_BEGIN>",
    "<TAG_END>",
    "\"\\\'\\\'\\\'\"",
    "\"\\\'\\\'\"",
    "\"[[\"",
    "\"[\"",
    "<HTML_ENTITY>",
    "\"]\"",
    "<INT_LINK_PREFIX>",
    "\"|\"",
    "<INT_LINK_SPACES>",
    "<INT_LINK_END>",
    "<INT_LINK_CONTENT>",
    "<INT_LINK_SYMBOL>",
  };

}
